spring.application.name=cloud-file-storage
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=20MB

minio.endpoint=http://localhost:9000
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
minio.bucket=cloud-file-storage

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}

server.tomcat.max-swallow-size=100MB

springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha